# Generated by Django 5.1.3 on 2025-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_points_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='extra_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='initiative_name',
            field=models.CharField(default='Без назви', max_length=255),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='initiative_type',
            field=models.CharField(default='Загальна', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Користувач', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
