# Generated by Django 5.1.3 on 2025-05-14 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='initiative_name',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='initiative_type',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='seeker',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='category',
            field=models.CharField(blank=True, choices=[('medical', 'Медична допомога'), ('food', 'Продукти харчування'), ('transport', 'Транспорт'), ('other', 'Інше')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='email',
            field=models.EmailField(default='nope', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'В процесі'), ('completed', 'Завершено')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
